# Generated by Django 3.0.5 on 2026-01-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20260121_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('consultationDate', models.DateField(auto_now=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('medicine', models.TextField(max_length=500)),
                ('extra_notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
