# Generated by Django 3.0.5 on 2026-01-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20260122_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('medicineName', models.CharField(max_length=100, null=True)),
                ('prescribeDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
