# Generated by Django 3.0.5 on 2026-01-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_prescriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='extra_notes',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
