# Generated by Django 3.0.5 on 2026-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_auto_20260123_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='consultationDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
