# Generated by Django 3.0.5 on 2026-01-23 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20260123_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescribeDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
