# Generated by Django 3.0.5 on 2026-01-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_patienthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Blood Test', 'Blood Test'), ('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('Urine Test', 'Urine Test'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('report_file', models.FileField(upload_to='lab_reports/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
