# Generated by Django 3.0.5 on 2026-02-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_auto_20260129_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
