# Generated by Django 3.0.5 on 2026-03-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_appointment_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctorName', 'appointmentDate', 'description'), name='unique_appointment'),
        ),
    ]
